systemtest: added `status scheduler` test to verify correct output

diff --git a/systemtests/tests/scheduler-backup/testrunner b/systemtests/tests/scheduler-backup/testrunner
--- a/systemtests/tests/scheduler-backup/testrunner
+++ b/systemtests/tests/scheduler-backup/testrunner
@@ -47,6 +47,44 @@ quit
 END_OF_DATA
 
 run_bareos "$@"
+
+#
+# Run test to check correct output of #`status scheduler job=...`
+# of a copy job whose client is disabled
+#
+cat <<END_OF_DATA >$tmp/bconcmds
+messages
+@$out $tmp/log3.out w
+status scheduler job=copy
+
+@$out $tmp/log4.out w
+disable client=bareos-fd
+status scheduler job=copy
+wait
+messages
+quit
+END_OF_DATA
+
+run_bconsole
+
+#check that `status scheduler job=...` returns scheduled copy jobs
+if ! grep "TestCycle               Level=Full" "$tmp"/log3.out; then
+  echo "'TestCycle               Level=Full' not found in $tmp/log3.out" >&2
+  estat=1
+fi
+
+#check that `status scheduler job=...` returns nothing when we disable the client
+if ! grep "TestCycle
+                            copy (disabled)
+
+           ====
+            " "$tmp"/log2.out ||
+    grep "TestCycle               Level=Full" "$tmp"/log4.out; then
+  echo "a scheduled job was listed in $tmp/log4.out" >&2
+  estat=1
+fi
+
+
 check_for_zombie_jobs storage=File
 stop_bareos
 
